[package]
name = "learn_rust"
version = "0.1.0"
authors = ["matianqi <mtqmx3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7.8"
